### ISSUE TITLE
hide chart on empty queryset

### ISSUE THREAD

**Issue by freevryheid** [dropseed/django-admincharts#45]
Chart is shown albeit blank.

**Comment by davegaeddert** [comment]
Thanks @freevryheid. I'll keep this in mind but my first reaction is that this doesn't really bother me. You can probably override `get_list_chart_config` and return `{}` if the queryset is empty if you want it to act differently in your project.
https://github.com/dropseed/django-admincharts/blob/494816de7fab75101332fc1ca3f033d4287dc64c/admincharts/admin.py#L36
